Release 1.2.0 (#39)
* Merge 'master' (v1.1.1 content) to 'develop'

* Update README-agent-install.md

* Fix wget flag by using two dashes

* Update version

* Update changelog

* Update version

* Update changelog

* Remove 1.2.0 release vendored gems

* Vendor cisco_node_utils version 1.3.0

* provider fixes for 1.3.0 node_utils gem

* Fix travis issues

* Remove grpc and google-protobuf gems

* Replace cisco_node_utils grpc files

* Update docs

* yaml fixes for cisco ohai plugins

* Recipe cleanup

* Update document links

* Update document links

* Add n8k references

* Update platorm references

* Fix bullet alignment issue

* Rubocop fixes

* Alpha order

* Update README-agent-install.md

* Refactor package provider to use rpm - qip (#32)

* Refactor package provider

* Rubocop fixes

* Rename method to something more intuitive

* Remove ruby 2.0.0 tests from travis.yml

* When 2.0.0 runs it pulls in foodcritic; foodcritic now requires ruby 2.1.0, so this 2.0.0 doesn't make sense anymore

* Remove ruby 2.0.0 tests from travis.yml

* When 2.0.0 runs it pulls in foodcritic; foodcritic now requires ruby 2.1.0, so this 2.0.0 doesn't make sense anymore

* command_config: undefined method 'previous' (#36)

* Remove ruby 2.0.0 tests from travis.yml

* When 2.0.0 runs it pulls in foodcritic; foodcritic now requires ruby 2.1.0, so this 2.0.0 doesn't make sense anymore

* command_config: undefined method 'previous' (#358)

* Symptom: Simple cc recipe with a faulty line of config:

cisco_command_config 'loop42' do
  action :update
  command '
    interface loopback42
    ip pim foo
  '
end

When chef-client runs the cc provider drops into a rescue which should first print out the parts of the config that were successfully processed and then do a raise, but instead we see:

    ```
    NoMethodError
    -------------
    undefined method `previous' for #<Cisco::CliError:0x00000005208488>

    ```

* Analysis: `client.rb` was refactored a few months ago, wherein the `previous` hash key was renamed to `successful_input`. The cc providers (both puppet & chef) never got updated with the new key name.
  * Ref: https://github.com/cisco/cisco-network-node-utils/blob/develop/lib/cisco_node_utils/client/nxapi/client.rb#L285

* Testing:

    ```
Linux# chef-client --once
 ...
Recipe: cisco-cookbook::cvh
  * cisco_command_config[loop42] action update[2016-07-15T19:20:57+04:00] INFO: Processing cisco_command_config[loop42] action update (cisco-cookbook::cvh line 24)

    ================================================================================
    Error executing action `update` on resource 'cisco_command_config[loop42]'
    ================================================================================

    Cisco::CliError
    ---------------
    The command 'ip pim foo' was rejected with error:
    % Invalid command

    ```

* Fix cisco_command_config bug (#37)

* change recipe to nvgen bgp neighbor as 9K does

* Delete old version of node_utils

* Revendor with cisco_node_utils 1.6

* Update references of N8k to n9k-F

* Update Copyright to 2017

* add build matrix for travis

* comment ruby version in travis

* add buff-extensions ver 1.0.0 to resolve travis failure

* fix rubocop errors

* Fix typo

* Add nio4r 1.2.1 to handle travis failure

* Install foodcritic version compatible with ruby 2.1.2

* Fix rubocop errors

* Update references of N8k to N9k-F

* Update License and Platform Support Table